server:
    port: 8085

spring:
    data:
        mongodb:
            uri: mongodb://campus:campus@localhost:27017/?authSource=admin
            database: CampusDB
    jackson:
            date-format: yyyy-MM-dd HH:mm:ss

logging:
    level:
        root: INFO
        org:
            springframework:
                context: INFO
                web: WARN
                data:
                    root: DEBUG
                    convert: INFO
                    mongodb:
                        driver: WARN
                        core:
                            MongoTemplate: DEBUG
                    beans:
                        factory:
                            support: INFO
                    boot:
                      autoconfigure: INFO
            hibernate:
                validator: INFO
            apache: WARN
            mongodb:
                driver: WARN
        sun: INFO
        javax: INFO